elementTable = {
'H': [1, 'hydrogen'],  'He': [2, 'helium'],  'Li': [3, 'lithium'],  'Be': [4, 'beryllium'],  'B': [5, 'boron'],
'C': [6, 'carbon'],  'N': [7, 'nitrogen'],  'O': [8, 'oxygen'],  'F': [9, 'fluorine'],  'Ne': [10, 'neon'],
'Na': [11, 'sodium'],  'Mg': [12, 'magnesium'],  'Al': [13, 'aluminium'],  'Si': [14, 'silicon'],  'P': [15, 'phosphorus'],
'S': [16, 'sulfur'],  'Cl': [17, 'chlorine'],  'Ar': [18, 'argon'],  'K': [19, 'potassium'],  'Ca': [20, 'calcium'],
'Sc': [21, 'scandium'],  'Ti': [22, 'titanium'],  'V': [23, 'vanadium'],  'Cr': [24, 'chromium'],  'Mn': [25, 'manganese'],
'Fe': [26, 'iron'],  'Co': [27, 'cobalt'],  'Ni': [28, 'nickel'],  'Cu': [29, 'copper'],  'Zn': [30, 'zinc'],
'Ga': [31, 'gallium'],  'Ge': [32, 'germanium'],  'As': [33, 'arsenic'],  'Se': [34, 'selenium'],  'Br': [35, 'bromine'],
'Kr': [36, 'krypton'],  'Rb': [37, 'rubidium'],  'Sr': [38, 'strontium'],  'Y': [39, 'yttrium'],  'Zr': [40, 'zirconium'],
'Nb': [41, 'niobium'],  'Mo': [42, 'molybdenum'],  'Tc': [43, 'technetium'],  'Ru': [44, 'ruthenium'],  'Rh': [45, 'rhodium'],
'Pd': [46, 'palladium'],  'Ag': [47, 'silver'],  'Cd': [48, 'cadmium'],  'In': [49, 'indium'],  'Sn': [50, 'tin'],
'Sb': [51, 'antimony'],  'Te': [52, 'tellurium'],  'I': [53, 'iodine'],  'Xe': [54, 'xenon'],  'Cs': [55, 'caesium'],
'Ba': [56, 'barium'],  'La': [57, 'lanthanum'],  'Ce': [58, 'cerium'],  'Pr': [59, 'praseodymium'],  'Nd': [60, 'neodymium'],
'Pm': [61, 'promethium'],  'Sm': [62, 'samarium'],  'Eu': [63, 'europium'],  'Gd': [64, 'gadolinium'],  'Tb': [65, 'terbium'],
'Dy': [66, 'dysprosium'],  'Ho': [67, 'holmium'],  'Er': [68, 'erbium'],  'Tm': [69, 'thulium'],  'Yb': [70, 'ytterbium'],
'Lu': [71, 'lutetium'],  'Hf': [72, 'hafnium'],  'Ta': [73, 'tantalum'],  'W': [74, 'tungsten'],  'Re': [75, 'rhenium'],
'Os': [76, 'osmium'],  'Ir': [77, 'iridium'],  'Pt': [78, 'platinum'],  'Au': [79, 'gold'],  'Hg': [80, 'mercury'],
'Tl': [81, 'thallium'],  'Pb': [82, 'lead'],  'Bi': [83, 'bismuth'],  'Po': [84, 'polonium'],  'At': [85, 'astatine'],
'Rn': [86, 'radon'],  'Fr': [87, 'francium'],  'Ra': [88, 'radium'],  'Ac': [89, 'actinium'],  'Th': [90, 'thorium'],
'Pa': [91, 'protactinium'],  'U': [92, 'uranium'],  'Np': [93, 'neptunium'],  'Pu': [94, 'plutonium'],  'Am': [95, 'americium'],
'Cm': [96, 'curium'],  'Bk': [97, 'berkelium'],  'Cf': [98, 'californium'],  'Es': [99, 'einsteinium'],  'Fm': [100, 'fermium'],
'Md': [101, 'mendelevium'],  'No': [102, 'nobelium'],  'Lr': [103, 'lawrencium'],  'Rf': [104, 'rutherfordium'],  'Db': [105, 'dubnium'],
'Sg': [106, 'seaborgium'],  'Bh': [107, 'bohrium'],  'Hs': [108, 'hassium'],  'Mt': [109, 'meitnerium'],  'Ds': [110, 'darmstadtium'],
'Rg': [111, 'roentgenium'],  'Cn': [112, 'copernicium'],  'Nh': [113, 'nihonium'],  'Fl': [114, 'flerovium'],  'Mc': [115, 'moscovium'],
'Lv': [116, 'livermorium'],  'Ts': [117, 'tennessine'],  'Og': [118, 'oganesson'],
}